# system configuration
system:
  # 修改为public可以关闭路由日志输出
  env: local
  addr: 8888
  db-type: mysql
  # 控制oss选择走本地还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  oss-type: local
  # 使用redis
  use-redis: false
  # 使用mongo
  use-mongo: false
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  # IP限制一个小时
  iplimit-time: 3600
  # 路由全局前缀
  router-prefix: ""
  # 严格角色模式 打开后权限将会存在上下级关系
  use-strict-auth: false
  # 禁用自动迁移数据库表结构，生产环境建议设为true，手动迁移
  disable-auto-migrate: false

# zap logger configuration
zap:
  level: info
  format: console
  prefix: "[BIGO/server]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
  keep-day: 10

# mysql connect configuration
mysql:
  path: "localhost"
  port: "3306"
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db-name: "bigo"
  username: "root"
  password: "admin"
  max-idle-conns: 1
  max-open-conns: 5
  log-mode: ""
  log-zap: false

jwt:
  signing-key: 'Jex(8efx'        # JWT 签名密钥
  expires-time: 604800           # Token 过期时间 (7天，单位秒)
  buffer-time: 86400             # Token 缓冲时间 (1天，单位秒)
  issuer: 'member'               # 签发者

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0 # 0代表一直开启，大于0代表限制次数
  open-captcha-timeout: 3600 # open-captcha大于0时才生效